# SPIRINT-2 DE-SERIALAIZATION:

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as img
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import PIL
import os
from PIL import Image


In [2]:
#here we are load the images(because we have to store the images to HDD)

In [3]:
#!PIP install PILLOW

In [4]:
from pickle import load

In [5]:
s1=load(open(r'C:\Users\dell\Desktop\MACHINE LEARNING PROJECTS\ml-handwritten-sprint1\Image data\random forest.pkl','rb'))

#for random forest

In [6]:
s2 = load(open(r'C:\Users\dell\Desktop\MACHINE LEARNING PROJECTS\ml-handwritten-sprint1\Image data\knn_classifier.pkl','rb'))

#KNN CLASSIFIER

In [7]:
s3=load(open(r'C:\Users\dell\Desktop\MACHINE LEARNING PROJECTS\ml-handwritten-sprint1\Image data\logistic_regression.pkl','rb'))

#for logistic regression


In [21]:
s4=load(open(r'C:\Users\dell\Desktop\MACHINE LEARNING PROJECTS\ml-handwritten-sprint1\Image data\decision tree.pkl','rb'))

#for Decision tree

In [9]:
#here we are taking one img:
img1=Image.open(r"C:\Users\dell\Desktop\MACHINE LEARNING PROJECTS\ml-handwritten-sprint1\Image data\sample_imgs\imgs\0.PNG")
img1.thumbnail((28,28))
img_resize=img1.resize((28,28))
array=np.array(img_resize)


In [10]:
two_d=array[:,:,0]

one_d=two_d.flatten()

In [11]:
two_d.shape

(28, 28)

In [12]:
array=np.array(one_d)

In [13]:
array

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   5,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   5, 126, 20

In [14]:
a = array.reshape(1,-1) 

In [15]:
a.shape

(1, 784)

In [16]:
s1.predict(a) #for random forest


array([0], dtype=int64)

In [17]:
s2.predict(a) #KNN classifier


array([0], dtype=int64)

In [18]:
s3.predict(a) #logistic regression


array([0], dtype=int64)

In [22]:
s4.predict(a) #decision tree


array([8], dtype=int64)

In [1]:
#for image[0] rfc,knn,logistic is giving same predicted output.but decision is not giving the same predicted output.